"""empty message

Revision ID: 781a0bc9a675
Revises: 
Create Date: 2023-08-28 20:17:50.834338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '781a0bc9a675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('is_kazakhstan', sa.Boolean(), nullable=True),
    sa.Column('last_online', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_message_telegramm_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('jwt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jwt_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('web_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.Column('is_answer', sa.Boolean(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['web_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('websockets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('socket_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websockets')
    op.drop_table('web_messages')
    op.drop_table('jwt')
    op.drop_table('web_users')
    # ### end Alembic commands ###
