"""empty message

Revision ID: b75547e4e7e7
Revises: 781a0bc9a675
Create Date: 2023-08-29 01:27:35.438017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75547e4e7e7'
down_revision: Union[str, None] = '781a0bc9a675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_messages', sa.Column('message_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_messages', 'message_type')
    # ### end Alembic commands ###
